### ISSUE TITLE
W1D5 has a sequential execution error

### ISSUE THREAD

**Issue by patrickmineault** [NeuromatchAcademy/course-content#122]
https://github.com/NeuromatchAcademy/course-content/pull/121

this seems fishy: 

https://github.com/NeuromatchAcademy/course-content/blob/588494f424d0f8aa1c3d5aa04df3d25e3f8f2810/ci/process_notebooks.py#L258

Can you compare two lists like that?

**Comment by AmeetR** [comment]
yes, but not recommended? if all elements at each index are equal, then that will return true.

**Comment by mwaskom** [comment]
Transferring my comment from #121 here:

Ah, maybe the check failure message is not clear. "Sequentially executed" checks for two things: (1) the execution count is sequentially ordered and (2) the execution counts start at 1. The notebooks that are failing the checks are specifically failing the second part.

Solution: Restart and run all. It's not enough to just "run all", because variables that were defined in cells that have since been deleted may still be hanging around in the kernel and influencing the results.

**Comment by mwaskom** [comment]
Closing with merge of clean/processed W1D5 notebooks. See #127 for followup.
