### ISSUE TITLE
Videos are not working

### ISSUE THREAD

**Issue by Anindita94-bit** [NeuromatchAcademy/course-content#220]
Is there any modifications are taking place? As I was going through the tutorials of optimal control, but those are removed and showing as private video.

**Comment by mwaskom** [comment]
Hi @Anindita94-bit — the existing links pointed at the "rough draft" version of the videos that were being used for the pre-course testing. They've been set to private now and will be replaced with public links to final versions as those come online over the course of the coming week.

**Comment by Anindita94-bit** [comment]
Thanks for the information. I couldn't able to cover the last week
lectures. Is there any probability that videos will be uploaded before the
end of the week?

Thanks and regards,
Anindita

**Comment by ashwin4ever** [comment]
It places the students who have hectic timelines at a disadvantage since some of the students like the above user would have covered most of the lectures. The videos either should have been made private from the start or the rough draft should be public. This makes those of us who weren't able to study them prior play catch up with those who might have covered it or downloaded the lectures in anticipation of it being made private later

**Comment by Anindita94-bit** [comment]
Now I can access the contents.

Thanks and Regards,
Anindita

On Mon, 6 Jul, 2020, 11:52 PM ANINDITA BHATTACHARJEE Res. Scholar, School
of Biomed. Engg. IIT (BHU), <aninditabhattacharjee.rs.bme18@itbhu.ac.in>
wrote:

**Comment by jerlich** [comment]
@mwaskom can close this now.
