### ISSUE TITLE
Suggestion to use urllib instead of wget for jupyter projects

### ISSUE THREAD

**Issue by RebeccaClarkson** [NeuromatchAcademy/course-content#245]
Hi! I'm Becky, I just happened to look over some of the code since I might be a panelist later on and was curious about the program. I noticed that some of the examples use wget to fetch remote assets - this involves opening a shell, which doesn't seem necessary given that you can use tools like urllib to fetch assets from within python. Curious if you have a reason for wanting to do it this way? (I poked around at doing a pull request, but figured since it was part of Google Collab - which I don't know much about - I'd leave it be)

Suggestion:
Replace
```
import os
fname = "kay_images.npz"
if not os.path.exists(fname):,
    !wget -qO $fname https://osf.io/ymnjv/download"
```
with
```
import urllib
import os
fname = "kay_images.npz"
if not os.path.isfile(fname): 
    urllib.request.urlretrieve("https://osf.io/ymnjv/download", fname)
```

(Though with the note that for python 3 can run into SSL_CERTIFICATE_VERIFY_FAILED error, which I solved with:
https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error
![image](https://user-images.githubusercontent.com/13040999/87124822-49321000-c23e-11ea-85c4-c12b79a68244.png)
)

Also, tried to run the wget command but then realized that wget wasn't installed on my computer - I'm guessing ```brew install wget``` would be the way? - I only bring that up because it could be a possible troubleshooting point as folks work through the examples.

**Comment by mwaskom** [comment]
Hi @RebeccaClarkson thanks for your suggestions. The important context here is that all of the material for the course is intended to be used on Google Colab, except in locations where that is not possible and we are offer support for a specific alternative. Unfortunately, while we expect that many students may want to download the materials and run them locally in Jupyter, we cannot offer support for issues that they encounter while doing so.

> Curious if you have a reason for wanting to do it this way?

I suspect that using `wget` to download a data file is more intuitive to the original content creators than doing it within Python. Normally you would separate data download and analysis and might do the former in a shell, but running the tutorials on Colab means that everything needs to be done in a notebook and repeated every time the VM recycles.

The wget solution works well, and the problem that you mention about SSL certificates seems challenging to solve. With that said, your issue did spark an internal discussion about whether we should do more error handling where we download data, and it's possible we will convert some code to pure Python solutions because detecting/recovering from errors will be easier with that approach.
