### ISSUE TITLE
W2D1 Tutorial 1 Video ordering

### ISSUE THREAD

**Issue by syncrostone** [NeuromatchAcademy/course-content#393]
W2D1 Tutorial 1 Video 3 introduces the interactive demo which comes before it in the notebook. It would make more sense for the order of these two cells to be switched, with the interactive demo coming after the video.

**Comment by mrkrause** [comment]
Since some students found the Week 1 tutorials overwhelming, we decided to make some exercises optional here, including Exercise 2B, is introduced in Video 3 introduces. 

I therefore moved the demo up, so that if you were going to skip 2B, you still tried the demo. As I recall, the video just briefly mentions it and suggests playing with it. If you did do Exercise 2B, we were hoping that you'd go back and try the demo again, now that you can predict the outcomes.

In both cases, I thought the text explained the demo pretty well-- *Was something specific missing that was only in the video?*

**Comment by syncrostone** [comment]
No, there was nothing missing from the text that was only in the video. Thanks for explaining why it was reordered -- the ordering makes sense given that 2B is now optional.

**Comment by mrkrause** [comment]
I guess we should mark Video 3 as optional too--I was trying to hedge our bets on how much people would get through. (And while I've got your attention, how was the length overall? Okay, or was everything rushed?

**Comment by syncrostone** [comment]
I'm zone 3 so I haven't taught it yet, so not sure. If video 3 is not marked as optional, I think it should be moved before the interactive demo. If it's optional, it can stay where it is.

Maybe a zone 1 or zone 2 TA can speak better to pacing. My group is pretty advanced in prior exposure to concepts so we've been getting through most bonus material in general, I'll try to remember to let you know if that's different today.
