### ISSUE TITLE
Error when opening notebooks: `Unrecognized runtime "nma"; defaulting to "python3"`

### ISSUE THREAD

**Issue by da5nsy** [NeuromatchAcademy/course-content#402]
Not sure whether this error has any impact (doesn't seem to) but thought I should flag it in case it does.

**Comment by mwaskom** [comment]
Opening the notebooks how?

**Comment by JesseLivezey** [comment]
I get the same error on that notebook.

**Comment by mwaskom** [comment]
The problem itself is innocuous; the notebook stores a record of the local environment it was last executed in, and it's saying Colab doesn't have such an environment, so you have to pick one it does have.

I'm not sure why that notebook alone is causing issues, though. It's possibly the last person that edited it checked it back into the github repo after running locally, rather than on Colab.
