### ISSUE TITLE
W2D2 Typos

### ISSUE THREAD

**Issue by ollimuh** [NeuromatchAcademy/course-content#410]
Tutorial 3, Section 2, second plot: labels (‘simulation’, ‘analytic solution’) are swapped.

**Comment by ollimuh** [comment]
In addition:
Small typo in T3 Exercise 1: ‘Distribution of bateria positions’

T4 Exercise 1: len(x2) = T-2, should be T-1 from description

**Comment by da5nsy** [comment]
Also:
## T2
> system express either

> system expressed either

**Comment by da5nsy** [comment]
Also:
## T3
Spare code chunk at end.

**Comment by mwaskom** [comment]
> Spare code chunk at end.

That's pretty much unavoidable, so I wouldn't worry about it when you see it.

**Comment by da5nsy** [comment]
> 
> 
> > Spare code chunk at end.
> 
> That's pretty much unavoidable, so I wouldn't worry about it when you see it.

I don't think other tutorials had it 😕 
(Not that it is at all an issue, just looks slightly messy)

**Comment by JesseLivezey** [comment]
Adding another note: in T1, the parenthesis in `args=(params)` should be removed (it is already a list).

**Comment by Ko-Ping** [comment]
Hello, just finish the W2D2 Tutorial 3
I realized in the helper function "var_comparison_plot" the xlabel and ylabel were swapped. Since we plot empirical variances at the x axis and analytical variances at the y axis, the set_xlabel should be "empirical equilibrium variance" and set_ylabel should be "analytic equilibrium variance" instead.
Thank you!
