### ISSUE TITLE
W2D4 Tut 1 - import error

### ISSUE THREAD

**Issue by SeeebO** [NeuromatchAcademy/course-content#429]
when importing the modules the following is missing:

from IPython.display import display

therefore the widget will not show/does not work

**Comment by mwaskom** [comment]
which widget?

**Comment by SeeebO** [comment]
probably all, since they need the display function

**Comment by mwaskom** [comment]
I just went through the instructor version of the current colab notebook and was able to run all of the widgets without any issues. We'll need you to be more specific about what you are doing and what happens.

**Comment by SeeebO** [comment]
Ok, 
surprises me because I think the display function (last line of each widget) has to be imported at some point and in my current instructor notebook ist wasn't (just refreshed)

when I added the line I suggested above

'from IPython.display import display'

in the #Imports block 
the widgets work

**Comment by mrkrause** [comment]
Can you post the error you got without that change?

**Comment by mwaskom** [comment]
Also please give some more information about how you are running the notebook. On colab? On jupyter on your own system? Some other cloud service? These details are important for helping us help you, specifically, and also everyone else taking part in NMA.

**Comment by SeeebO** [comment]
Ok, sure 
got this error on coloab with chrome. Can't reproduce though. 
Now it works even when I do not add the statement, but others (see slack) seem to have encountered the issue as well.

**Comment by SeeebO** [comment]
but I saved the error message:

TypeError: 'module' object is not callable 

This was when trying to execute the first widget after running all the previous cells on colab/chrome

**Comment by mwaskom** [comment]
@SeeebO I'm confused ... did you get an ImportError or a TypeError?

**Comment by SeeebO** [comment]
sorry - I was very unclear in the first message
Had a pretty long day and was waiting for the final tutorial to arrive to prepare tomorrow and thought this might be a fast fix

I received the error I posted - a TypeError - that I could resolve by adding the import command in the beginning of the code

**Comment by mwaskom** [comment]
Here is how I understand the problem:

1) the original (prepod version) notebook did `from IPython import display`. `display` here is a module. But it does not appear to be used in the notebook

2) the final notebook (what is on colab now) does not explicitly import `IPython.display.display`, but that's OK because IPython imports it an injects it into the default namespace (check by opening a blank notebook and calling `display()`).

3) you seem to have been using some intermediate version of the notebook that imported `IPython.display` but then called it as if it were a function. that wouldn't have passed our CI, so I'm not sure how you ended up with it, but it's possible to see how it would have happened during the rewrite from (1) to (2).

I think we can close this as no longer relevant?

**Comment by SeeebO** [comment]
sure, sorry for any confusion
