### ISSUE TITLE
W1D1 Hint at bottom of exercise 2

### ISSUE THREAD

**Issue by TaravanViegen** [NeuromatchAcademy/course-content#529]
"You might also want to restrict the range to see the shape of the distribution when focusing on relatively short or long ISIs. Hint: the **second** argument to plt.hist sets the interval to define bins over." Currently says third.

**Comment by mwaskom** [comment]
I think that comment is correct, if a bit confusing. The signature for `plt.hist` is:

```python
plt.hist(x, bins=None, range=None, ...
```

So you can do, e.g. `plt.hist(x, 10, (0, 2))` and it will draw 10 bins between 0 and 2. This is redundant with `plt.hist(x, np.linspace(0, 2, 10))` and so it's *also* true that the second argument can control the range, but it does so less conveniently.

**Comment by TaravanViegen** [comment]
I see. I think it threw me off because the third argument in any previous calls to plt.hist had histtype="stepfilled" in the third position. I would probably go with: "Hint: add an argument to plt.hist to set the interval to define bins over."

**Comment by mrkrause** [comment]
It's confusing in context because the hint is just below this code. 
 ```
 plt.hist(single_neuron_isis, bins=50, histtype="stepfilled")
  plt.axvline(single_neuron_isis.mean(), color="orange", label="Mean ISI")
  plt.xlabel("ISI duration (s)")
  plt.ylabel("Number of spikes")
  plt.legend()
```
so, the third argument that we *show* doesn't do anything and the 2nd argument is sorta-related.

Maybe something like would work?
"`plt.hist` also takes a `range` argument, a tuple consisting of the lowest and highest edges of the bin. Try setting this to zoom in on <whatever they're supposed to see>..."

**Comment by mwaskom** [comment]
There are two confusions here: 

- A confusion between *parameters* and *arguments*
- A confusion between enumerating keyword vs positional arguments.

What is true is that the third *parameter* of `plt.hist` controls the range of the plot. The third *argument* that gets passed in the context here does not control the range, because it was passed as a keyword argument.

I agree that the best way to avoid confusion without elaborating on these pedantic distinctions is just to reference the name of the parameter (`range`) directly. I don't think we need to tell them exactly how to use it, because the docstring for `plt.hist` does that.
