### ISSUE TITLE
[CI] Colab link update fails if branch name is missing

### ISSUE THREAD

**Issue by bgalbraith** [NeuromatchAcademy/course-content#551]
The current colab badge link update (reasonably) assumes a branch name, e.g. `.../blob/branch-name/...`, to find and replace with `master`. However, in the event no branch name is present in the (invalid) link, e.g. `.../blob/...`, the regex fails and doesn't update.

It's not entirely clear how the branch name got dropped in the observed case (https://github.com/NeuromatchAcademy/course-content/pull/549), but we should probably try to cover this edge case.

**Comment by mwaskom** [comment]
I think the problem is that the [regex](https://github.com/NeuromatchAcademy/course-content/blob/abf0fae52c20ccb34cab593241fbc7e52963e77b/ci/process_notebooks.py#L345) assumes branch names will be made of up "word" characters, which includes `_` but not `-` (which was what was used on that branch.

Should be a trivial fix to make it match on `[-\w]+` but I guess you'd want to test it....

**Comment by mwaskom** [comment]
I think we ran into a couple of similar issues last year when someone (you, maybe?) were using a hierarchical branch naming scheme (e.g. `fix/W2D5`) which is a trickier pattern to match in the context of a url...
