### ISSUE TITLE
Tutorial CI as a separate repo

### ISSUE THREAD

**Issue by mmyros** [NeuromatchAcademy/course-content#553]
Hi all, 

I have recently used tutorial CI to make teaching materials and found it extremely useful. Would there be any interest in packaging it up for general use? Perhaps we could upload the contents of `CI` folder to PyPI after packaging it up and then `pip install` it in `.github/workflow`.  I would be happy to help. 

Thanks
Max

**Comment by mwaskom** [comment]
We've split the CI tools off into a [separate repository](https://github.com/neuromatchAcademy/nmaci) so that they can be shared between the CN and DL courses this year. I'm not sure how much appetite there is for supporting the tools as a general library — I think they'll stay pretty closely tied to NMA conventions. But if you would like to develop tutorial resources that hew closely to those conventions, hopefully they will be useful.
