### ISSUE TITLE
JOSE: Formatting

### ISSUE THREAD

**Issue by PaulScotti** [NeuromatchAcademy/course-content#603]
I think there is a minor error in the pdf: “All lectures and tutorial are available online [permalink]” I do not see a link here  in the pdf.

This is reviewer feedback associated with submission to JOSE: openjournals/jose-reviews#118

**Comment by thartbm** [comment]
We now have an OSF repository with the GitHub content, as well as a JupyterBook version (doesn't have solutions, but nicer for students). Which is here: https://osf.io/93wna as well as a back up of the movies (in lower resolution) here: https://osf.io/79wv2/. I will need to be authorized to add a GitHub add-on to link the OSF repositories to the original repositories, but then they can be registered as permanent archives. Hope this solves it?

**Comment by thartbm** [comment]
Turns out OSF has specific size restrictions, so the data sets had to be split into several repositories. But that seems all solved in this registered project: https://doi.org/10.17605/OSF.IO/CFN4U

The table of pre-requisites is now in the wiki page there (no longer in the paper), and there are 5 "links" to other registrations: 1 with videos of lectures, and 4 with data sets.
