### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by arashash** [NeuromatchAcademy/course-content#642]
I was wondering if the requirements.txt tested on all the notebooks? it looks pretty short and versions are not included

I am planning on creating a virtual environment for offline access for all the students using this.

**Comment by mwaskom** [comment]
It is [what's used](https://github.com/NeuromatchAcademy/course-content/blob/master/.github/workflows/notebook-pr.yaml#L52) for the automated CI, so yes.

It was a conscious decision to keep the set of required libraries small and limited to core scientific Python libraries.

This is actually a subset of the libraries used across the tutorials; there are a few one-off days that use more domain-specific libraries (i.e. the HMM library used for stochastic processes), but the rule is that tutorials using libraries not defined in this requirements set have to pip install them within the notebook itself.

There are no versions because there is not, AFAIK, a public record of the versions installed on Colab, so it seemed better to test against "latest versions" rather than pin on versions that will fall out of sync with Colab.

**Comment by arashash** [comment]
Thanks Michael for the clarification. I'll find a workaround.

**Comment by mwaskom** [comment]
May be useful:

```
[mlw-mbpro tutorials]{master $}$ git grep '!pip'
Bonus_UnsupervisedLearning/Tutorial2.ipynb:    "!pip install plotly --quiet\n",
Bonus_UnsupervisedLearning/student/Tutorial2.ipynb:    "!pip install plotly --quiet\n",
W0D4_Calculus/W0D4_Tutorial1.ipynb:    "!pip install sympy --quiet\n",
W0D4_Calculus/student/W0D4_Tutorial1.ipynb:    "!pip install sympy --quiet\n",
W3D2_HiddenDynamics/W3D2_Tutorial2.ipynb:    "!pip install hmmlearn --quiet\n",
W3D2_HiddenDynamics/W3D2_Tutorial4.ipynb:    "!pip install pykalman --quiet\n",
W3D2_HiddenDynamics/student/W3D2_Tutorial2.ipynb:    "!pip install hmmlearn --quiet\n",
W3D2_HiddenDynamics/student/W3D2_Tutorial4.ipynb:    "!pip install pykalman --quiet\n",
W3D5_NetworkCausality/W3D5_Tutorial4.ipynb:    "!pip install statsmodels\n",
W3D5_NetworkCausality/student/W3D5_Tutorial4.ipynb:    "!pip install statsmodels\n",
```
