### ISSUE TITLE
W1D1 Deep learning

### ISSUE THREAD

**Issue by kaushik-pallavi** [NeuromatchAcademy/course-content#927]
Interactive Demo 3.3: Solving XOR

Do you think we can solve the discrete XOR (only 4 possibilities) with only 2 hidden units?
The correct answer shows to be "no".

We can solve XOR using MLP (2 hidden units in a hidden layer). So I think the answer should be yes.

**Comment by koerding** [comment]
Do you have a solution with ReLUs?

**Comment by koerding** [comment]
ah hold on. It says discrete ;) you are right.

**Comment by kaushik-pallavi** [comment]
Thank you for addressing the issue :)

**Comment by koerding** [comment]
Thanks again. Here is my description of solution "“Awesome. Indeed, yes. We take the two points for which the output should be 1 and dedicate one of the hidden units to each of them. Each of theses  ReLU functions are diagonal and tuned so that only for one of those two points the output is 1. In the end, we add these two together hidden units together. And voila - discrete xor."

**Comment by kaushik-pallavi** [comment]
Perfect! Thank you :)
